[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shopify-backend"
version = "1.0.0"
description = "E-commerce backend with FastAPI"
requires-python = ">=3.8"
authors = [
    {name = "Aravind K Ashok"}
]